# Generated by Django 3.1.6 on 2021-07-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodrequest',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
