# Generated by Django 3.1.6 on 2021-07-07 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0004_auto_20210704_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_need',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
