# Generated by Django 3.1.6 on 2021-07-07 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0005_bloodrequest_blood_need'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_need',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
