# Generated by Django 3.1.6 on 2021-07-07 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0006_auto_20210707_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='blood_need',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_need_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_need_time',
            field=models.TimeField(default=datetime.datetime.now, null=True),
        ),
    ]
