# Generated by Django 3.1.6 on 2021-07-07 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0007_auto_20210707_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='blood_need_date',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='blood_need_time',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_need',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
