# Generated by Django 3.1.6 on 2021-07-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_auto_20210219_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddoner',
            name='group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=50),
        ),
    ]
