# Generated by Django 3.1.6 on 2021-07-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210707_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
